import type { AddonRecord, ProductRecord } from "@/lib/domain";

export const products: ProductRecord[] = [
  {
    id: "gratinada",
    slug: "brasa-gourmet",
    name: "Brasa Gourmet",
    shortDescription: "Ostras gratinadas prontas para servir.",
    fullDescription:
      "Uma seleção de ostras gratinadas com acabamento dourado, preparada para chegar quente e pronta para a mesa.",
    type: "gratinated",
    category: "experiencias",
    price: 149.9,
    stock: 30,
    active: true,
    featured: true,
    image: "/images/ostra-gratinada.png",
    includedItems: ["Limões selecionados", "Molho especial da casa", "Embalagem térmica"],
    preparationHours: 18,
    approximateVolume: "12 unidades",
    displayOrder: 1,
  },
  {
    id: "baby",
    slug: "experiencia-degustacao",
    name: "Experiência Degustação",
    shortDescription: "Ostras baby para uma primeira experiência.",
    fullDescription:
      "Porção leve e delicada de ostras baby, acompanhada por limões selecionados e molho especial.",
    type: "fresh",
    category: "experiencias",
    price: 69.9,
    stock: 50,
    active: true,
    featured: true,
    image: "/images/kit-degustacao.png",
    includedItems: ["Limões selecionados", "Molho especial da casa", "Gelo e sal"],
    preparationHours: 18,
    approximateVolume: "6 unidades",
    displayOrder: 2,
  },
  {
    id: "tradicional",
    slug: "experiencia-happy-hour",
    name: "Experiência Happy Hour",
    shortDescription: "Ostras tradicionais para compartilhar.",
    fullDescription:
      "Uma porção equilibrada de ostras tradicionais para encontros, brindes e fins de tarde.",
    type: "fresh",
    category: "experiencias",
    price: 79.9,
    stock: 50,
    active: true,
    featured: true,
    image: "/images/kit-happy-hour.png",
    includedItems: ["Limões selecionados", "Molho especial da casa", "Gelo e sal"],
    preparationHours: 18,
    approximateVolume: "8 unidades",
    displayOrder: 3,
  },
  {
    id: "premium",
    slug: "reserva-premium",
    name: "Reserva Premium",
    shortDescription: "Ostras grandes para ocasiões especiais.",
    fullDescription:
      "Seleção premium de ostras grandes, montada sob demanda para uma apresentação marcante.",
    type: "fresh",
    category: "experiencias",
    price: 129.9,
    stock: 25,
    active: true,
    featured: true,
    image: "/images/kit-premium.png",
    includedItems: ["Limões selecionados", "Molho especial da casa", "Gelo e sal"],
    preparationHours: 24,
    approximateVolume: "10 unidades",
    displayOrder: 4,
  },
  ...[
    ["agua-sem-gas", "Água mineral sem gás", "Garrafa 500 ml", 6],
    ["agua-com-gas", "Água mineral com gás", "Garrafa 500 ml", 7],
    ["coca-cola", "Coca-Cola", "Lata 350 ml", 8.5],
    ["guarana", "Guaraná", "Lata 350 ml", 8.5],
    ["fanta", "Fanta Laranja", "Lata 350 ml", 8.5],
    ["brahma", "Brahma", "Lata 350 ml", 9.9],
    ["heineken", "Heineken", "Long neck 330 ml", 13.9],
    ["itaipava", "Itaipava", "Lata 350 ml", 8.9],
    ["sauvignon-blanc", "Sauvignon Blanc", "Vinho branco seco, 750 ml", 89.9],
    ["chardonnay", "Chardonnay", "Vinho branco, 750 ml", 109.9],
    ["espumante-brut", "Espumante Brut", "Espumante nacional, 750 ml", 119.9],
  ].map(([id, name, description, price], index) => ({
    id: String(id),
    slug: String(id),
    name: String(name),
    shortDescription: String(description),
    fullDescription: String(description),
    type: "beverage" as const,
    category: "bebidas",
    price: Number(price),
    stock: 100,
    active: true,
    featured: false,
    includedItems: [],
    preparationHours: 0,
    displayOrder: 10 + index,
  })),
];

export const addons: AddonRecord[] = [
  {
    id: "limao-extra",
    name: "Limão extra",
    description: "Porção extra de limões selecionados.",
    price: 4.9,
    stock: 100,
    active: true,
    productIds: ["gratinada", "baby", "tradicional", "premium"],
  },
  {
    id: "molho-especial",
    name: "Molho especial",
    description: "Pote adicional do molho da casa.",
    price: 8.9,
    stock: 80,
    active: true,
    productIds: ["gratinada", "baby", "tradicional", "premium"],
  },
  {
    id: "gelo-extra",
    name: "Gelo extra",
    description: "Saco extra para manter a apresentação.",
    price: 6,
    stock: 100,
    active: true,
    productIds: ["baby", "tradicional", "premium"],
  },
  {
    id: "kit-descartavel",
    name: "Kit descartável",
    description: "Guardanapos, talheres e pratos.",
    price: 12.9,
    stock: 100,
    active: true,
    productIds: [],
  },
  {
    id: "embalagem-premium",
    name: "Embalagem premium",
    description: "Apresentação especial para presente.",
    price: 24.9,
    stock: 40,
    active: true,
    productIds: [],
  },
];

export const deliveryWindows = [
  "10h às 12h",
  "12h às 14h",
  "14h às 16h",
  "16h às 18h",
  "18h às 20h",
];

export const getProduct = (id: string) =>
  products.find((product) => product.id === id && product.active);

export const getAddon = (id: string) =>
  addons.find((addon) => addon.id === id && addon.active);
